version: "3.9"
services:
  my-app:
    image: aqi-data-finder
    environment:
      - API_KEY=b560e16cd8b011983ffcc2d9efca08cf
    ports:
      - "8081:8081"
    networks:
      my-network:
        ipv4_address: 172.16.238.11
networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24